package com.myspace.t1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agelist implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public agelist() {
    }




}