package com.myspace.t1;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class enumlist implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public enumlist() {
	}

	public java.util.List<String> list() {
		java.util.List<String> list = new java.util.ArrayList<>();
		list.add("1L");
		list.add("2L");
		return list;
	}
	public List<String> getlist() {
		java.util.List<String> list = new java.util.ArrayList<>();
		list.add("1=1岁");
		list.add("2=2岁");
		return list;
	}

}