package com.myspace.t1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class People implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long age;

	private java.lang.String high;

	public People() {
	}

	public java.lang.Long getAge() {
		return this.age;
	}

	public void setAge(java.lang.Long age) {
		this.age = age;
	}

	public java.lang.String getHigh() {
		return this.high;
	}

	public void setHigh(java.lang.String high) {
		this.high = high;
	}

	public People(java.lang.Long age, java.lang.String high) {
		this.age = age;
		this.high = high;
	}

}